name: main

on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: windows-latest
    env:
      msbuild_path: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe
      msvs_version: 2022
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true
          cache: npm
      - name: Install the dependencies
        run: npm ci
      - name: Build the native modules
        run: npm run rebuild
      - name: Build the app
        run: npm run build
      - name: Upload the build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: release/
