name: test

on:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Get the version
        id: appVersion
        shell: bash
        run: echo "appVersion=$(jq -r .version package.json)" >> $GITHUB_OUTPUT && cat $GITHUB_OUTPUT
      - uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.appVersion.outputs.appVersion }}
          body: ${{ steps.appVersion.outputs.appVersion }}
          token: ${{ secrets.GH_TOKEN }}
