name: test

on:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - run: echo ${{ secrets.GH_TOKEN }} > token.txt
      - uses: ncipollo/release-action@v1
        with:
          tag: test
          artifacts: "token.txt"
          token: ${{ secrets.GH_TOKEN }}
